<?php

class Model_Post extends Orm\Model
{
	protected static $_properties = array(
		'id',
		'content',
                'image_url',
		'id_user',
            'delete_status',
            
/**
 * auto generated by oil
 */
		
/**
 * auto generated by oil
 */
	);
/**
 * auto generated by oil
 * @var unknown
 */

/*	protected static $_observers = array(
		'Orm\Observer_CreatedAt' => array(
			'events' => array('before_insert'),
			'mysql_timestamp' => true,
		),
		'Orm\Observer_UpdatedAt' => array(
			'events' => array('before_update'),
			'mysql_timestamp' => false,
		),
	);
*/
/**
 * auto generated by oil
 * @var unknown
 */
	protected static $_table_name = 'post';
	
	protected static $_primary_key = array('id');

}
?>