<?php

class Model_User extends Orm\Model
{
	protected static $_properties = array(
		'id',
		'email',
		'password',
/**
 * auto generated by oil
 */
		'created_at',
//		'updated_at',
/**
 * auto generated by oil
 */
	);
/**
 * auto generated by oil
 * @var unknown
 */

/**
 * auto generated by oil
 * @var unknown
 */
	protected static $_table_name = 'users';
	
	protected static $_primary_key = array('id');

}
?>